name: Echo Commit Hash

on:
  push:
    branches:
      - main

jobs:
  echo-commit:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Echo the full commit hash
      - name: Echo Full Commit Hash
        run: |
          echo "Full Commit Hash: $GITHUB_SHA"

      - name: Echo Short Commit Hash
        run: |
          SHORT_COMMIT=$(echo "${GITHUB_SHA}" | cut -c1-7)
          echo "Short Commit Hash: $SHORT_COMMIT"
      - name: Echo Short SHA
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "Short sha: $SHORT_SHA"    
