name: Echo Commit Hash

on:
  push:
    branches:
      - main

jobs:
  echo-commit:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Echo the full commit hash
      - name: Echo Full Commit Hash
        run: echo "Full Commit Hash: $GITHUB_SHA"

      # Step 3: Echo the short commit hash
      - name: Echo Short Commit Hash
        run: echo "Short Commit Hash: ${GITHUB_SHA::7}"
